name: recipe_ai
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  google_generative_ai: ^0.4.6
  image_picker: ^1.1.2
  drift: ^2.15.0
  path_provider: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  drift_dev: ^2.15.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - .env
